image:
  repository: eu.gcr.io/kyma-project/test-infra/alpine-kubectl
  tag: v20190325-ff66a3a
  pullPolicy: IfNotPresent

test:
  id: perfass
  assetNumber: 50
  assetSource:
    url: https://minio.lysy-testuje.wookiee.kyma.online/test/kyma-master.zip
    filter: /docs/service-catalog/docs/kyma-0.8.1.zip
    mode: package
  bucket:
    name: perfass-bucket
    region: us-east-1
