apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install,pre-delete,post-delete"
  name: {{ template "perfass.name" . }}
  namespace: kyma-system
  labels:
    app: {{ template "perfass.fullname" . }} 
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - assetstore.kyma-project.io
  resources:
  - buckets
  - clusterbuckets
  - assets
  - clusterassets
  verbs:
  - list
  - create
  - get
  - delete

