apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kyma-system
  name: {{ template "perfass.fullname" . }}-templates
  labels:
    app: {{ template "perfass.name" . }}
    chart: {{ template "perfass.chart" . }}
data:
  asset: |-
{{ include (print $.Template.BasePath "/_asset_tpl") . | indent 4 }}
  bucket: |-
{{ include (print $.Template.BasePath "/_bucket_tpl") . | indent 4 }}